//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class attendance
    {
        public int att_id { get; set; }
        [DisplayName("Student Name")]
        public string att_name { get; set; }
        [DisplayName("Batch ID")]
        public string att_batch { get; set; }
        [DisplayName("Session")]
        public Nullable<int> att_session { get; set; }
        [DisplayName("Month")]
        public string att_month { get; set; }
        [DisplayName("Year")]
        public Nullable<int> att_year { get; set; }
        [DisplayName("Attendance")]
        public string att_attendance { get; set; }
    
        public virtual student student { get; set; }
        public virtual batch batch { get; set; }
    }
}
