//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class book
    {
        public int b_id { get; set; }
        [DisplayName("Book Name"), Required(ErrorMessage = "Please fill this field")]
        public string b_name { get; set; }
        [DisplayName("Writer"), Required(ErrorMessage = "Please fill this field")]
        public string b_write { get; set; }
        [DisplayName("Topic Belongs to")]
        public string b_topic { get; set; }
        [DisplayName("Book")]
        public string b_book { get; set; }
        [Required(ErrorMessage = "Please fill this field")]
        public HttpPostedFileBase bookFile { get; set; }
    }
}
