//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class coordinator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coordinator()
        {
            this.batch = new HashSet<batch>();
        }
        [DisplayName("Coordinator ID"), Required(ErrorMessage = "Please fill this field")]
        public string coord_id { get; set; }
        [DisplayName("Coordinator Name"), Required(ErrorMessage = "Please fill this field")]
        public string coord_name { get; set; }
        [DisplayName("Email Address"), DataType(DataType.EmailAddress), Required(ErrorMessage = "Please fill this field")]
        public string coord_email { get; set; }
        [DisplayName("Address"), Required(ErrorMessage = "Please fill this field")]
        public string coord_address { get; set; }
        [DisplayName("Contact Number"), Required(ErrorMessage = "Please fill this field")]
        public long coord_contact { get; set; }
        [DisplayName("Salary"), DataType(DataType.Currency), Required(ErrorMessage = "Please fill this field")]
        public decimal coord_salary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batch> batch { get; set; }
    }
}
