//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class diploma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public diploma()
        {
            this.course = new HashSet<course>();
        }
        [DisplayName("Diploma Name"), Required(ErrorMessage = "Please fill this field")]
        public string dip_name { get; set; }
        [DisplayName("Duration"), Required(ErrorMessage = "Please fill this field")]
        public string dip_duration { get; set; }
        [DisplayName("Package"), Required(ErrorMessage = "Please fill this field")]
        public decimal dip_package { get; set; }
        public int dip_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course> course { get; set; }
    }
}
