//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class examAttend
    {
        public int exat_id { get; set; }
        [DisplayName("Exam Name")]
        public int exat_name { get; set; }
        [DisplayName("Student")]
        public string exat_enrollement { get; set; }
        [DisplayName("Status")]
        public string exat_status { get; set; }
        [DisplayName("Date")]
        public System.DateTime exat_date { get; set; }
        [DisplayName("Time")]
        public System.TimeSpan exat_time { get; set; }
        [DisplayName("Lab Number")]
        public string exat_lab { get; set; }
    
        public virtual exam exam { get; set; }
        public virtual student student { get; set; }
    }
}
