//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LMSEntities : DbContext
    {
        public LMSEntities()
            : base("name=LMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attendance> attendance { get; set; }
        public virtual DbSet<batch> batch { get; set; }
        public virtual DbSet<book> book { get; set; }
        public virtual DbSet<coordinator> coordinator { get; set; }
        public virtual DbSet<course> course { get; set; }
        public virtual DbSet<diploma> diploma { get; set; }
        public virtual DbSet<exam> exam { get; set; }
        public virtual DbSet<examAttend> examAttend { get; set; }
        public virtual DbSet<student> student { get; set; }
        public virtual DbSet<teacher> teacher { get; set; }
        public virtual DbSet<userDetails> userDetails { get; set; }
    }
}
