//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class batch
    {
        [DisplayName("Batch Code")]
        public string bat_id { get; set; }

        [DisplayName("Slot")]
        public string bat_slot { get; set; }

        [DisplayName("Day")]
        public string bat_days { get; set; }

        [DisplayName("Teacher")]
        public string bat_teacher { get; set; }
        [DisplayName("Coordinator")]
        public string bat_coordinator { get; set; }
        [DisplayName("Lab Number")]
        public Nullable<int> bat_lab { get; set; }
        [DisplayName("Semester")]
        public Nullable<int> bat_sem { get; set; }

        [DisplayName("Status")]
        public string bat_status { get; set; }
    
        public virtual coordinator coordinator { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
