//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class userDetails
    {
        [DisplayName("User ID")]
        public string u_id { get; set; }
        [DisplayName("User Password"), DataType(DataType.Password)]
        public string u_password { get; set; }
        [DisplayName("Position")]
        public string u_role { get; set; }
        [NotMapped]
        [DisplayName("Old Password"), DataType(DataType.Password)]
        public string oldPassword { get; set; }
        [NotMapped]
        [DisplayName("New Password"), DataType(DataType.Password)]
        public string newPassword { get; set; }
        [NotMapped]
        [DisplayName("Confirm Password"), DataType(DataType.Password)]
        public string confirmPassword { get; set; }
    }
}
